name: sendPluginMessages
main: com.minecats.sendpluginmessages.SendPluginMessages
version: 1.0
description: Yikes! Make this worse
author: cindyk
website: http://www.minecats.com
depend: [Vault]

commands:
  sendplug:
    description: Show a list of title commands
    usage: /<command> - Show a list of commands
